{{- if .Values.migration.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "gophprofile.fullname" . }}-migrate
  labels:
    {{- include "gophprofile.labels" . | nindent 4 }}
    app.kubernetes.io/component: migration
  {{- if .Values.migration.hook }}
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-weight: "-5"
    helm.sh/hook-delete-policy: before-hook-creation,hook-succeeded
  {{- end }}
spec:
  backoffLimit: {{ .Values.migration.backoffLimit }}
  template:
    metadata:
      labels:
        {{- include "gophprofile.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: migration
        app.kubernetes.io/part-of: gophprofile
    spec:
      restartPolicy: OnFailure
      serviceAccountName: {{ include "gophprofile.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: migrate
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - /app/migrate
          env:
            - name: SERVICE_NAME
              value: {{ printf "%s-migrate" (include "gophprofile.fullname" .) | quote }}
          envFrom:
            - configMapRef:
                name: {{ include "gophprofile.fullname" . }}-config
            - secretRef:
                name: {{ include "gophprofile.secretName" . }}
          securityContext:
            {{- toYaml .Values.containerSecurityContext | nindent 12 }}
          resources:
            {{- toYaml .Values.migration.resources | nindent 12 }}
{{- end }}
