{{- if .Values.secret.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "gophprofile.secretName" . }}
  labels:
    {{- include "gophprofile.labels" . | nindent 4 }}
type: Opaque
stringData:
  DATABASE_URL: {{ .Values.secret.databaseUrl | quote }}
  S3_ACCESS_KEY: {{ .Values.secret.s3AccessKey | quote }}
  S3_SECRET_KEY: {{ .Values.secret.s3SecretKey | quote }}
  RABBITMQ_URL: {{ .Values.secret.rabbitmqUrl | quote }}
{{- end }}
