apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "gophprofile.fullname" . }}-server
  labels:
    {{- include "gophprofile.labels" . | nindent 4 }}
    app.kubernetes.io/component: server
spec:
  replicas: {{ .Values.server.replicas }}
  selector:
    matchLabels:
      {{- include "gophprofile.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: server
  template:
    metadata:
      labels:
        {{- include "gophprofile.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: server
        app.kubernetes.io/part-of: gophprofile
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: /metrics
        prometheus.io/port: {{ .Values.server.port | quote }}
    spec:
      serviceAccountName: {{ include "gophprofile.serviceAccountName" . }}
      terminationGracePeriodSeconds: 30
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: server
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.server.port }}
              protocol: TCP
          env:
            - name: SERVICE_NAME
              value: {{ printf "%s-server" (include "gophprofile.fullname" .) | quote }}
          envFrom:
            - configMapRef:
                name: {{ include "gophprofile.fullname" . }}-config
            - secretRef:
                name: {{ include "gophprofile.secretName" . }}
          securityContext:
            {{- toYaml .Values.containerSecurityContext | nindent 12 }}
          resources:
            {{- toYaml .Values.server.resources | nindent 12 }}
          startupProbe:
            httpGet:
              path: /health
              port: http
            {{- toYaml .Values.server.startupProbe | nindent 12 }}
          livenessProbe:
            httpGet:
              path: /health
              port: http
            {{- toYaml .Values.server.livenessProbe | nindent 12 }}
          readinessProbe:
            httpGet:
              path: /health
              port: http
            {{- toYaml .Values.server.readinessProbe | nindent 12 }}
