apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - configmap.yaml
  - secret.example.yaml
  - serviceaccount.yaml
  - rbac.yaml
  - migration-job.yaml
  - server-deployment.yaml
  - worker-deployment.yaml
  - server-service.yaml
  - worker-service.yaml
  - ingress.yaml
  - hpa.yaml
  - servicemonitor.yaml
  - networkpolicy.yaml
  - poddisruptionbudget.yaml
