apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: gophprofile-server
  namespace: gophprofile
  labels:
    app.kubernetes.io/name: gophprofile
    app.kubernetes.io/component: server
    app.kubernetes.io/part-of: gophprofile
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: gophprofile
      app.kubernetes.io/component: server
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: gophprofile-worker
  namespace: gophprofile
  labels:
    app.kubernetes.io/name: gophprofile
    app.kubernetes.io/component: worker
    app.kubernetes.io/part-of: gophprofile
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: gophprofile
      app.kubernetes.io/component: worker
