apiVersion: v1
kind: Secret
metadata:
  name: gophprofile-secrets
  namespace: gophprofile
  labels:
    app.kubernetes.io/name: gophprofile
    app.kubernetes.io/part-of: gophprofile
type: Opaque
stringData:
  DATABASE_URL: postgres://gophprofile:gophprofile@postgres:5432/gophprofile?sslmode=disable
  S3_ACCESS_KEY: minioadmin
  S3_SECRET_KEY: minioadmin
  RABBITMQ_URL: amqp://guest:guest@rabbitmq:5672/
