apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: gophprofile-server
  namespace: gophprofile
  labels:
    app.kubernetes.io/name: gophprofile
    app.kubernetes.io/component: server
    app.kubernetes.io/part-of: gophprofile
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: gophprofile
      app.kubernetes.io/component: server
  endpoints:
    - port: http
      path: /metrics
      interval: 30s
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: gophprofile-worker
  namespace: gophprofile
  labels:
    app.kubernetes.io/name: gophprofile
    app.kubernetes.io/component: worker
    app.kubernetes.io/part-of: gophprofile
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: gophprofile
      app.kubernetes.io/component: worker
  endpoints:
    - port: metrics
      path: /metrics
      interval: 30s
