apiVersion: v1
kind: ServiceAccount
metadata:
  name: gophprofile
  namespace: gophprofile
  labels:
    app.kubernetes.io/name: gophprofile
    app.kubernetes.io/part-of: gophprofile
automountServiceAccountToken: false
