apiVersion: v1
kind: Service
metadata:
  name: gophprofile-worker
  namespace: gophprofile
  labels:
    app.kubernetes.io/name: gophprofile
    app.kubernetes.io/component: worker
    app.kubernetes.io/part-of: gophprofile
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: gophprofile
    app.kubernetes.io/component: worker
  ports:
    - name: metrics
      port: 9091
      targetPort: metrics
      protocol: TCP
